# Generated by Django 5.2.12 on 2026-03-28 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_userprofile_id"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="userprofile",
            table="accounts_userprofile",
        ),
    ]
