"""
Django base settings for money_journey project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', "django-insecure--+vh3!a0gzjnbsx@wj_ybxbtf@k*_(o6$2$^6xtq==-l#9s)55")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',')
if DEBUG and not any(ALLOWED_HOSTS):
    ALLOWED_HOSTS = ['*', 'localhost', '127.0.0.1', 'testserver']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "accounts",
    "funds",
    "analytics",
    "savings_calculator",
    'django_crontab',  # For scheduled tasks
]

# 定时任务环境变量配置
CRONTAB_COMMAND_PREFIX = (
    f"MYSQL_HOST={os.getenv('MYSQL_HOST', '')} "
    f"MYSQL_PORT={os.getenv('MYSQL_PORT', '')} "
    f"MYSQL_DATABASE={os.getenv('MYSQL_DATABASE', '')} "
    f"MYSQL_USER={os.getenv('MYSQL_USER', '')} "
    f"MYSQL_PASSWORD={os.getenv('MYSQL_PASSWORD', '')} "
    f"DJANGO_SETTINGS_MODULE=money_journey.settings "
    f"PUSHPLUS_TOKEN={os.getenv('PUSHPLUS_TOKEN', '')} "
)

# 定时任务配置
CRONJOBS = [
    # 格式: ('定时表达式', '应用.模块.函数', '>> 日志文件路径')
    # 查询过期任务
    ('0 19-21 * * *', 'analytics.tasks.check_outdated_records', '>> /app/logs/crontab.log'),
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Whitenoise for static files
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "money_journey.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "money_journey.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('MYSQL_DATABASE', ''),
        'USER': os.environ.get('MYSQL_USER', ''),
        'PASSWORD': os.environ.get('MYSQL_PASSWORD', ''),
        'HOST': os.environ.get('MYSQL_HOST', ''),
        'PORT': os.environ.get('MYSQL_PORT', ''),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Whitenoise configuration for static files
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
WHITENOISE_MAX_AGE = 31536000  # 1 year cache
WHITENOISE_USE_FINDERS = True
WHITENOISE_MANIFEST_STRICT = False

LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# CSRF settings - development defaults, override in production
CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'False') == 'True'
CSRF_COOKIE_HTTPONLY = os.environ.get('CSRF_COOKIE_HTTPONLY', 'False') == 'True'
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', 'http://localhost:8000,http://127.0.0.1:8000').split(',')

# Session settings - development defaults, override in production
SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', 'False') == 'True'
SESSION_COOKIE_SAMESITE = os.environ.get('SESSION_COOKIE_SAMESITE', 'Lax')

# Logging configuration
# 创建日志目录
LOG_DIR = '/app/logs'
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    
    # 格式化器
    'formatters': {
        'verbose': {
            'format': '{levelname}-{asctime}-{module}-{process:d}-{thread:d}: {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname}: {message}',
            'style': '{',
        },
        'detailed': {
            'format': '[{asctime}]-{levelname}-{name}: {message}',
            'datefmt': '%Y-%m-%d %H:%M:%S',
            'style': '{',
        },
    },
    
    # 过滤器
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    
    # 处理器
    'handlers': {
        # 控制台输出（开发环境）
        'console': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],  # 只在DEBUG=True时启用
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        
        # 控制台输出（生产环境）
        'console_prod': {
            'level': 'INFO',
            'filters': ['require_debug_false'],  # 只在DEBUG=False时启用
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        
        # 错误日志文件
        'file_error': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'error.log'),
            'maxBytes': 10 * 1024 * 1024,  # 10MB
            'backupCount': 5,  # 保留5个备份
            'formatter': 'detailed',
        },
        
        # 常规日志文件
        'file_info': {
            'level': 'INFO',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'info.log'),
            'when': 'midnight',  # 每天午夜分割
            'backupCount': 30,  # 保留30天
            'formatter': 'detailed',
        },
        
        # 按日分割的文件
        'file_daily': {
            'level': 'INFO',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'daily.log'),
            'when': 'midnight',
            'interval': 1,
            'backupCount': 7,
            'formatter': 'detailed',
        },
        
        # 邮件通知（错误时发送邮件）
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'include_html': True,
        },
    },
    
    # 记录器配置
    'loggers': {
        # Django 框架自身的日志
        'django': {
            'handlers': ['console', 'console_prod', 'file_error'],
            'level': 'INFO',
            'propagate': False,
        },
        
        # 数据库查询日志
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG' if os.environ.get('DEBUG', 'False') == 'True' else 'INFO',
            'propagate': False,
        },
        
        # 请求日志
        'django.request': {
            'handlers': ['file_error', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        
        # 安全日志
        'django.security': {
            'handlers': ['file_error'],
            'level': 'WARNING',
            'propagate': False,
        },
        
        # 您自己应用的日志
        'accounts': {  # 替换为您的应用名
            'handlers': ['console', 'file_info', 'file_error'],
            'level': 'DEBUG',
            'propagate': False,
        },

        # 您自己应用的日志
        'analytics': {  # 替换为您的应用名
            'handlers': ['console', 'file_info', 'file_error'],
            'level': 'DEBUG',
            'propagate': False,
        },

        # 您自己应用的日志
        'savings_calculator': {  # 替换为您的应用名
            'handlers': ['console', 'file_info', 'file_error'],
            'level': 'DEBUG',
            'propagate': False,
        },
        
        # 第三方库的日志
        'requests': {
            'handlers': ['console'],
            'level': 'WARNING',
        },
        
        # 根记录器（捕获所有未指定的日志）
        '': {
            'handlers': ['console', 'console_prod', 'file_info', 'file_error'],
            'level': 'WARNING',
        },
    },
}
