# Generated by Django 5.2.12 on 2026-03-28 10:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FundRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bank",
                    models.CharField(
                        choices=[
                            ("ICBC", "工商银行"),
                            ("CCB", "建设银行"),
                            ("ABC", "农业银行"),
                            ("RCB", "农商银行"),
                            ("BOC", "中国银行"),
                            ("CMB", "招商银行"),
                            ("CITIC", "中信银行"),
                            ("SPDB", "浦发银行"),
                            ("CIB", "兴业银行"),
                            ("CMBC", "民生银行"),
                            ("PINGAN", "平安银行"),
                            ("ALIPAY", "支付宝"),
                            ("WECHAT", "微信支付"),
                            ("HPP", "公积金"),
                            ("STOCK", "股票"),
                            ("OTHER", "其他银行"),
                        ],
                        max_length=50,
                        verbose_name="银行",
                    ),
                ),
                (
                    "owner",
                    models.CharField(
                        blank=True,
                        help_text="自动从用户信息填充",
                        max_length=100,
                        verbose_name="所有者",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CURRENT", "活期存款"),
                            ("SAVINGS", "储蓄存款"),
                            ("TIME_DEPOSIT", "定期存款"),
                            ("WEALTH_MANAGEMENT", "理财产品"),
                            ("FUND", "基金"),
                            ("STOCK", "股票"),
                            ("BOND", "债券"),
                            ("INSURANCE", "保险"),
                            ("OTHER", "其他"),
                        ],
                        max_length=50,
                        verbose_name="类别",
                    ),
                ),
                (
                    "savings_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "存续中"),
                            ("MATURED", "已到期"),
                            ("WITHDRAWN", "已取出"),
                            ("ROLLED_OVER", "已续存"),
                        ],
                        default="ACTIVE",
                        max_length=50,
                        verbose_name="储蓄状态",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="金额",
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="利率(%)",
                    ),
                ),
                (
                    "deposit_period",
                    models.IntegerField(
                        blank=True,
                        help_text="单位为年",
                        null=True,
                        verbose_name="存期(年)",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="到期日"),
                ),
                (
                    "due_month",
                    models.CharField(
                        blank=True,
                        help_text="格式: YYYY-MM",
                        max_length=7,
                        null=True,
                        verbose_name="到期月",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="记录所属用户",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "资金记录",
                "verbose_name_plural": "资金记录",
                "db_table": "records_fundrecord",
                "ordering": ["-created_at"],
            },
        ),
    ]
