# Generated by Django 5.2.12 on 2026-03-29 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundsnapshot",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
