# Generated by Django 5.2.12 on 2026-03-29 13:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0002_alter_fundsnapshot_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundsnapshot",
            name="snapshot_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="快照时间"
            ),
        ),
    ]
