# Generated by Django 5.2.12 on 2026-03-28 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0002_alter_fundrecord_id"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="fundrecord",
            table="funds_fundrecord",
        ),
    ]
