# Generated by Django 5.2.12 on 2026-04-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0003_alter_fundsnapshot_snapshot_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundrecord",
            name="category",
            field=models.CharField(
                choices=[
                    ("CURRENT", "活期存款"),
                    ("SAVINGS", "储蓄存款"),
                    ("WEALTH_MANAGEMENT", "理财产品"),
                    ("FUND", "基金"),
                    ("STOCK", "股票"),
                    ("BOND", "债券"),
                    ("INSURANCE", "保险"),
                    ("OTHER", "其他"),
                ],
                max_length=50,
                verbose_name="类别",
            ),
        ),
        migrations.AlterField(
            model_name="fundrecord",
            name="savings_status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "存续中"),
                    ("WITHDRAWN", "已取出"),
                    ("ROLLED_OVER", "已续存"),
                ],
                default="ACTIVE",
                max_length=50,
                verbose_name="储蓄状态",
            ),
        ),
    ]
