# Generated by Django 5.2.12 on 2026-03-28 13:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0003_alter_fundrecord_table"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FundSnapshot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "snapshot_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="快照时间"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="总金额"
                    ),
                ),
                ("record_count", models.IntegerField(verbose_name="记录数量")),
                (
                    "owner_summary",
                    models.JSONField(default=dict, verbose_name="所有者汇总"),
                ),
                (
                    "bank_summary",
                    models.JSONField(default=dict, verbose_name="银行汇总"),
                ),
                (
                    "category_summary",
                    models.JSONField(default=dict, verbose_name="类别汇总"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "资金快照",
                "verbose_name_plural": "资金快照",
                "ordering": ["-snapshot_date"],
            },
        ),
    ]
