# Generated by Django 5.2.12 on 2026-04-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0004_alter_fundrecord_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundrecord",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="开始日期"),
        ),
    ]
