# Generated by Django 5.2.12 on 2026-04-05 02:00

from django.db import migrations
from datetime import timedelta

def populate_start_date(apps, schema_editor):
    FundRecord = apps.get_model('funds', 'FundRecord')
    
    # 批量更新已有记录
    records = FundRecord.objects.filter(
        due_date__isnull=False,
        deposit_period__isnull=False
    )
    
    for record in records:
        record.start_date = record.due_date - timedelta(days=365 * record.deposit_period)
        record.save(update_fields=['start_date'])


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0005_fundrecord_start_date"),
    ]

    operations = [
        migrations.RunPython(populate_start_date, migrations.RunPython.noop)
    ]
