# Generated by Django 5.2.12 on 2026-04-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0006_auto_20260405_1000"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundrecord",
            name="start_date",
            field=models.DateField(
                blank=True, editable=False, null=True, verbose_name="开始日期"
            ),
        ),
    ]
