# Generated by Django 5.2.12 on 2026-04-05 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0007_alter_fundrecord_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fundsnapshot',
            name='user',
            field=models.ForeignKey(blank=True, help_text='快照所属用户', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fund_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
        migrations.AlterField(
            model_name='fundsnapshot',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_fund_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
    ]
