# Generated by Django 5.2.12 on 2026-04-05 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0008_fundsnapshot_user_alter_fundsnapshot_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundsnapshot',
            name='owner_summary',
        ),
    ]
