# Generated by Django 5.2.12 on 2026-04-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0009_remove_fundsnapshot_owner_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundsnapshot',
            name='user',
        ),
        migrations.AddField(
            model_name='fundsnapshot',
            name='owner',
            field=models.CharField(blank=True, help_text='快照所属用户', max_length=100, verbose_name='所有者'),
        ),
    ]
