# Generated by Django 6.0.3 on 2026-03-27 09:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fundrecord",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="记录所属用户",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="关联用户",
            ),
        ),
        migrations.AlterField(
            model_name="fundrecord",
            name="category",
            field=models.CharField(
                choices=[
                    ("CURRENT", "活期存款"),
                    ("SAVINGS", "储蓄存款"),
                    ("TIME_DEPOSIT", "定期存款"),
                    ("WEALTH_MANAGEMENT", "理财产品"),
                    ("FUND", "基金"),
                    ("STOCK", "股票"),
                    ("BOND", "债券"),
                    ("INSURANCE", "保险"),
                    ("OTHER", "其他"),
                ],
                max_length=50,
                verbose_name="类别",
            ),
        ),
        migrations.AlterField(
            model_name="fundrecord",
            name="owner",
            field=models.CharField(
                blank=True,
                help_text="自动从用户信息填充",
                max_length=100,
                verbose_name="所有者",
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False,
                        help_text="用户注册后需要管理员批准才能登录",
                        verbose_name="已批准",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户资料",
                "verbose_name_plural": "用户资料",
            },
        ),
    ]
