# Generated by Django 6.0.3 on 2026-03-27 12:52

from django.db import migrations, models


def convert_months_to_years(apps, schema_editor):
    """将存款期限从月转换为年（除以12，四舍五入）"""
    FundRecord = apps.get_model('records', 'FundRecord')
    # 更新所有有存期值的记录
    records = FundRecord.objects.filter(deposit_period__isnull=False)
    for record in records:
        # 将月转换为年，四舍五入到最接近的整数
        months = record.deposit_period
        if months is not None:
            years = round(months / 12)
            # 如果四舍五入后为0，设为1（至少1年）
            if years == 0:
                years = 1
            record.deposit_period = years
            record.save(update_fields=['deposit_period'])


def reverse_conversion(apps, schema_editor):
    """反向转换：将年转换回月（乘以12）"""
    FundRecord = apps.get_model('records', 'FundRecord')
    records = FundRecord.objects.filter(deposit_period__isnull=False)
    for record in records:
        years = record.deposit_period
        if years is not None:
            record.deposit_period = years * 12
            record.save(update_fields=['deposit_period'])


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0002_fundrecord_user_alter_fundrecord_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundrecord",
            name="bank",
            field=models.CharField(
                choices=[
                    ("ICBC", "工商银行"),
                    ("CCB", "建设银行"),
                    ("ABC", "农业银行"),
                    ("RCB", "农商银行"),
                    ("BOC", "中国银行"),
                    ("CMB", "招商银行"),
                    ("CITIC", "中信银行"),
                    ("SPDB", "浦发银行"),
                    ("CIB", "兴业银行"),
                    ("CMBC", "民生银行"),
                    ("PINGAN", "平安银行"),
                    ("ALIPAY", "支付宝"),
                    ("WECHAT", "微信支付"),
                    ("HPP", "公积金"),
                    ("STOCK", "股票"),
                    ("OTHER", "其他银行"),
                ],
                max_length=50,
                verbose_name="银行",
            ),
        ),
        migrations.AlterField(
            model_name="fundrecord",
            name="deposit_period",
            field=models.IntegerField(
                blank=True, help_text="单位为年", null=True, verbose_name="存期(年)"
            ),
        ),
        migrations.RunPython(
            code=convert_months_to_years,
            reverse_code=reverse_conversion,
        ),
    ]
