# Generated by Django 6.0.3 on 2026-03-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0003_alter_fundrecord_bank_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(
                blank=True, help_text="用户姓名", max_length=100, verbose_name="姓名"
            ),
        ),
    ]
