# Generated by Django 5.2.12 on 2026-03-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0004_userprofile_first_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="first_name",
        ),
        migrations.AlterField(
            model_name="fundrecord",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
